apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.job.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.job.name }}
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ .Values.job.name }}
          labels:
            app: {{ .Values.job.name }}
            visualize: "true"
        spec:
          serviceAccountName: {{ .Values.serviceAccountName }}
          containers:
          - name: {{ .Values.job.name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: S3_CONTENT_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: upp-exports-s3.content.prefix
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: upp-exports-s3.bucket
            - name: BUCKET_REGION
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: upp-exports-s3.region
            - name: S3_CONCEPT_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: upp-exports-s3.concept.prefix
            - name: S3_ARCHIVES_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: upp-exports-s3.archives.prefix
            - name: MAX_NO_OF_GOROUTINES
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: zipper.max.goroutines
            - name: IS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: zipper.s3.isenabled
            - name: YEAR_TO_START
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: zipper.s3.yeartostart
            resources:
{{ toYaml .Values.resources | indent 14 }}
          restartPolicy: Never

