apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.job.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    visualize: "true"
    app: {{ .Values.job.name }}
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.job.name }}
            visualize: "true"
        spec:
          containers:
          - name: {{ .Values.job.name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: BUCKET_NAME
              value:  "{{ .Values.env.bucket.name }}"
            - name: S3_CONTENT_FOLDER
              value: "{{ .Values.env.bucket.content.folder }}"
            - name: S3_CONCEPT_FOLDER
              value: "{{ .Values.env.bucket.concept.folder }}"
            - name: S3_ARCHIVES_FOLDER
              value: "{{ .Values.env.bucket.archives.folder }}"
            - name: MAX_NO_OF_GOROUTINES
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: zipper.max.goroutines
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: aws.access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: aws.secret_access_key
            - name: IS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: zipper.s3.isenabled
            - name: YEAR_TO_START
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: zipper.s3.yeartostart
            resources:
    {{ toYaml .Values.resources | indent 12 }}
          restartPolicy: Never

