# Default values for zipper-s3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
job:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
image:
  repository: coco/zipper-s3
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 2Gi
    cpu: 1
